### ISSUE TITLE
Enhanced Sessions for Fedora

### ISSUE THREAD

**Issue by carwyn** [jterry75/xrdp-init#13]
Just to let you know I'm trying to get enhanced sessions working on Fedora 27/28 too:

https://bugzilla.redhat.com/show_bug.cgi?id=1553453

**Comment by jterry75** [comment]
This is great! I read the posts and it seems to be mostly working. Would you be interested in writing a similar config script for setting up Fedora and we can put it in this repo for now to help others on board?

**Comment by carwyn** [comment]
Sure, will test it a bit more. Wasn't sure what the colourd bits were needed for?

For Fedora I can also throw a build of xrdp onto https://copr.fedorainfracloud.org/ to ease testing for people (saves them recompiling the SRPM).

It makes a huge difference to mouse lag, thank you for working on this.
