### ISSUE TITLE
rmmod: ERROR: ../libkmod/libkmod-module.c:793 kmod_module_remove_module() could not remove 'vsock': Device or resource busy

### ISSUE THREAD

**Issue by mradeschnig** [jterry75/xrdp-init#23]
I get errors for the three rmmod commands in the script. Do I have to install a special tool to do that or prepare the environment somehow?

ssr@VirtualBox:~/xrdp-init/ubuntu/18.04$ sudo ./install.sh
Hit:1 http://linux.teamviewer.com/deb stable InRelease
Hit:2 http://linux.teamviewer.com/deb preview InRelease                        
Hit:3 http://at.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:4 http://at.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Hit:6 http://at.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Hit:7 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease  
Reading package lists... Done                      
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xrdp is already the newest version (0.9.5-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
rmmod: ERROR: ../libkmod/libkmod-module.c:793 kmod_module_remove_module() could not remove 'vsock': Device or resource busy
rmmod: ERROR: could not remove module vsock: Device or resource busy
modprobe: ERROR: could not insert 'hv_sock': No such device
Install is complete.
Reboot your machine to begin using XRDP.

**Comment by jterry75** [comment]
The `rmmod` errors are likely a red herring. If you didn't have xrdp running with a `vsock` configuration its likely you didn't have `vsock` loaded yet. The one that is concerning is that you don't have `hv_sock`. Are you running with a new enough version of bionic that they added the `CONFIG_HYPERV_VSOCKETS=y`? What happens after you reboot?

**Comment by jterry75** [comment]
This change hopefully resolved your issues. Please reactivate if it didn't.
