### ISSUE TITLE
EnhancedSessionTransportType Error

### ISSUE THREAD

**Issue by wnelbach** [jterry75/xrdp-init#26]
When I try to run the powershell script, I get an error with this parameter. I've looked everywhere for some direction, but no luck. I figured I'd ask here given some of you have gotten past this section.

**Comment by jterry75** [comment]
What is the error you are seeing in PS?

**Comment by wnelbach** [comment]
Well..uhhhh. I missed a key phrase "you need to be on Insider Builds" doh! Could that bewhy powershell is not recognizing EnhancedSessionTransportType?

**Comment by jterry75** [comment]
Yes. This is a new flag that is only available on insider builds at the moment.

**Comment by wnelbach** [comment]
Thanks for your help jterry75. I signed up for MS Insider and now have the flag.
