### ISSUE TITLE
Can't get Ubuntu 18.04 working with Server 2019 1803 17733.10000

### ISSUE THREAD

**Issue by ghost** [jterry75/xrdp-init#52]
I can't seem to find any mention of this actually being supported on Server 2019.  I was able to follow the instructions to get this working on Windows 10 1803 at home.  I believe I followed the same directions (I think!) on my work Server 2019 1803 computer and I can't get enhanced session to light up.

Happy to provide logs, but not sure how/which!

**Comment by cwilhit** [comment]
What version of Ubuntu 18.04 are you using? Is it their Desktop edition or Server edition?

Using Windows Server as the host should not impact things--just so long as you can still set the transport type to "HvSocket".

**Comment by jerickmsft** [comment]
@cwilhit Apologies for the radio silence. I am running Ubuntu 18.04.1 LTS 64-bit Desktop.
For the host I am now running Server 2019 18282 and I have run
`Set-VM -VMName Ubuntu18 -EnhancedSessionTransportType HvSocket`

./install.sh says:
`Install is complete. Reboot your machine to being using XRDP.`

but when I reboot I get the normal login prompt.
